name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: notely-472417
      IMAGE_URI: us-central1-docker.pkg.dev/notely-472417/notely-ar-repo/notely
      SHA_TAG: ${{ github.sha }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # use a real available version or "stable"
          go-version: "stable"

      - name: Build app
        run: ./scripts/buildprod.sh

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Set project
        run: gcloud config set project "$PROJECT_ID"

      - name: Build and push Docker image (Cloud Build)
        run: |
          gcloud builds submit \
            --tag "$IMAGE_URI:$SHA_TAG" \
            --tag "$IMAGE_URI:latest" \
            .

      # Optional
      - name: Use gcloud CLI
        run: gcloud info
