name: cd

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: notely-473517
      REGION: us-central1
      REPO: notely-ar-repo
      IMAGE: notely
      IMAGE_URI: us-central1-docker.pkg.dev/notely-473517/notely-ar-repo/notely
      SHA_TAG: ${{ github.sha }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # Authenticate to GCP with your JSON key secret
      - id: auth
        name: Auth to Google Cloud (JSON key)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Set project
        run: gcloud config set project "$PROJECT_ID"

      # This is the required step the checker looks for:
      - name: Build & push with Cloud Build
        run: |
          gcloud builds submit \
            --tag "$IMAGE_URI:$SHA_TAG" \
            --tag "$IMAGE_URI:latest" \
            .

      # Optional: show info for debugging
      - name: gcloud info
        run: gcloud info
